#!/bin/sh

CFG = /etc/bluetooth/main.conf

if [ "install" = "$1" ]; then

  grep -q "##bt-tether##begin##" "$CFG" \
    || echo -e "##bt-tether##begin##\nDisablePlugins = network\n##bt-tether##end##" >> "$CFG"

elif [ "uninstall" = "$1" ]; then

  sed -i -e "/##bt-tether##begin##/,/##bt-tether##end##/ d" "$CFG"

else
  echo "Usage: $0 install | uninstall"
  exit 1
fi


