#!/bin/sh -e

NAME=bt-tether
VERSION="$1"
RELEASE=${2:-1}
DST="$NAME-$VERSION-$RELEASE"

if [ -z "$VERSION" ]; then
  printf "Usage: $0 version [release]\n"
  exit 1
fi

cd "$(dirname "$0")"/..

mkdir -p target

rm -rf "target/$DST" "target/$DST.tgz"
mkdir -p "target/$DST"
cp -r files src "target/$DST"
mkdir -p "target/$DST/files/usr/local/share/doc/bt-tether"
cp LICENCE README.md "target/$DST/files/usr/local/share/doc/bt-tether"
tar -C target -zcf "target/$DST.tgz" "$DST"
rm -rf "target/$DST"

rpm/bt-tether.spec.gen $VERSION $RELEASE > "target/$DST.spec"

